import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/landingpagethree">LandingpageThree</Link>
        </li>
        <li>
          <Link to="/landingpagefour">LandingpageFour</Link>
        </li>
        <li>
          <Link to="/landingpage">Landingpage</Link>
        </li>
        <li>
          <Link to="/landingpagetwo">LandingpageTwo</Link>
        </li>
        <li>
          <Link to="/completeprofile">Completeprofile</Link>
        </li>
        <li>
          <Link to="/courses">Courses</Link>
        </li>
        <li>
          <Link to="/certification">Certification</Link>
        </li>
        <li>
          <Link to="/landingpageone">LandingpageOne</Link>
        </li>
        <li>
          <Link to="/uiuxpage">UIUXpage</Link>
        </li>
        <li>
          <Link to="/frontenddevelopmentpage">Frontenddevelopmentpage</Link>
        </li>
        <li>
          <Link to="/backenddevelopmentpage">Backenddevelopmentpage</Link>
        </li>
        <li>
          <Link to="/flutterdevelopmentpage">Flutterdevelopmentpage</Link>
        </li>
        <li>
          <Link to="/angularjspage">AngularJSpage</Link>
        </li>
        <li>
          <Link to="/googlecloudpage">GoogleCloudpage</Link>
        </li>
        <li>
          <Link to="/javapage">Javapage</Link>
        </li>
        <li>
          <Link to="/reactjspage">ReactJSpage</Link>
        </li>
        <li>
          <Link to="/dsapage">DSApage</Link>
        </li>
        <li>
          <Link to="/digitalmarketingpage">Digitalmarketingpage</Link>
        </li>
        <li>
          <Link to="/aboutuspage">Aboutuspage</Link>
        </li>
        <li>
          <Link to="/contactuspage">Contactuspage</Link>
        </li>
        <li>
          <Link to="/hackathonpageone">HackathonpageOne</Link>
        </li>
        <li>
          <Link to="/hackathonpage">Hackathonpage</Link>
        </li>
        <li>
          <Link to="/uiuxcontestpageone">UIUXContestpageOne</Link>
        </li>
        <li>
          <Link to="/uiuxcontestpage">UIUXContestpage</Link>
        </li>
        <li>
          <Link to="/mentorshippage">Mentorshippage</Link>
        </li>
        <li>
          <Link to="/mentorpage">Mentorpage</Link>
        </li>
        <li>
          <Link to="/booknowchoosedatepage">Booknowchoosedatepage</Link>
        </li>
        <li>
          <Link to="/applyasamentorpageone">ApplyasamentorpageOne</Link>
        </li>
        <li>
          <Link to="/campusambassadorpage">Campusambassadorpage</Link>
        </li>
        <li>
          <Link to="/placement">Placement</Link>
        </li>
        <li>
          <Link to="/signup">Signup</Link>
        </li>
        <li>
          <Link to="/login">Login</Link>
        </li>
        <li>
          <Link to="/blogs">Blogs</Link>
        </li>
        <li>
          <Link to="/blogsone">BlogsOne</Link>
        </li>
        <li>
          <Link to="/educatorstwo">EducatorsTwo</Link>
        </li>
        <li>
          <Link to="/campushiring">CampusHiring</Link>
        </li>
        <li>
          <Link to="/applyform">Applyform</Link>
        </li>
        <li>
          <Link to="/termsconditions">Termsconditions</Link>
        </li>
        <li>
          <Link to="/privacypolicy">PrivacyPolicy</Link>
        </li>
        <li>
          <Link to="/faqs">FAQS</Link>
        </li>
        <li>
          <Link to="/thinkwhtcommunity">ThinkWhtCommunity</Link>
        </li>
        <li>
          <Link to="/mentorpageone">MentorpageOne</Link>
        </li>
        <li>
          <Link to="/applyasamentorpage">Applyasamentorpage</Link>
        </li>
        <li>
          <Link to="/resetpassword">Resetpassword</Link>
        </li>
        <li>
          <Link to="/formthinkwhtcommunity">Formthinkwhtcommunity</Link>
        </li>
        <li>
          <Link to="/refundpolicy">RefundPolicy</Link>
        </li>
        <li>
          <Link to="/placementguaranteefullstackdevelopment">
            PlacementguaranteeFullstackdevelopment
          </Link>
        </li>
        <li>
          <Link to="/placementguaranteefullstackdevelopmentone">
            PlacementguaranteeFullstackdevelopmentOne
          </Link>
        </li>
        <li>
          <Link to="/placementguaranteemernstackdevelopment">
            PlacementguaranteeMernstackdevelopment
          </Link>
        </li>
        <li>
          <Link to="/masterinjavascript">Masterinjavascript</Link>
        </li>
        <li>
          <Link to="/devops">DevOps</Link>
        </li>
        <li>
          <Link to="/bda">BDA</Link>
        </li>
        <li>
          <Link to="/hr">HR</Link>
        </li>
        <li>
          <Link to="/datascience">DataScience</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
